import 'dart:ui' as ui;

import 'package:flame/cache.dart';

import 'models.dart';

/// Every PNG in assets/sprites that the game draws. Generated by tools/sprites.
class Sprites {
  static const cropIds = ['radish', 'wheat', 'carrot', 'strawberry', 'corn'];
  static const animalIds = ['chicken', 'sheep', 'cow'];

  static final names = <String>[
    'soil_dry', 'soil_wet', 'soil_locked', 'soil_next', 'pen',
    for (final c in cropIds)
      for (var s = 0; s < 4; s++) 'crop_${c}_$s',
    for (final a in animalIds) 'animal_$a',
    'bubble_crop', 'bubble_egg', 'bubble_wool', 'bubble_milk',
    'decor_tree', 'decor_bush', 'decor_flowers', 'decor_tuft', 'decor_barn',
    'icon_coin', 'icon_star', 'fx_sparkle',
  ];

  final Map<String, ui.Image> _images;
  Sprites._(this._images);

  ui.Image operator [](String name) => _images[name] ?? (throw ArgumentError('No sprite "$name"'));

  /// Growth stage sprite for a plot: 0..2 while growing, 3 when ripe.
  static int cropStage(PlotStage stage, double progress) =>
      stage == PlotStage.ripe ? 3 : (progress * 3).floor().clamp(0, 2);

  static String productBubble(String animalKind) => switch (animalKind) {
        'chicken' => 'bubble_egg',
        'sheep' => 'bubble_wool',
        _ => 'bubble_milk',
      };

  static Future<Sprites>? _shared;

  /// Loaded once and shared by every screen.
  static Future<Sprites> load() => _shared ??= _load();

  static Future<Sprites> _load() async {
    final images = Images(prefix: 'assets/sprites/');
    try {
      await images.loadAll([for (final n in names) '$n.png']);
    } catch (_) {
      _shared = null; // allow a retry instead of caching the failure
      rethrow;
    }
    return Sprites._({for (final n in names) n: images.fromCache('$n.png')});
  }
}
